In [93]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.datasets import load_boston
from random import seed
from random import randrange
from csv import reader
from math import sqrt
from sklearn import preprocessing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from prettytable import PrettyTable
from sklearn.linear_model import SGDRegressor
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error

In [94]:
X = load_boston().data
Y = load_boston().target

In [95]:
scaler = preprocessing.StandardScaler().fit(X)
X = scaler.transform(X)

In [96]:
clf = SGDRegressor()
clf.fit(X, Y)
print(mean_squared_error(Y, clf.predict(X)))

22.85459284611785


In [97]:
clf.coef_

array([-0.73780116,  0.52233109, -0.4997822 ,  0.82765991, -1.00729517,
        3.25625465, -0.37734528, -2.23974156,  0.85577561, -0.45101561,
       -1.92181463,  0.95563149, -3.26761137])

In [98]:
print(type(X))

<class 'numpy.ndarray'>


In [99]:
X.shape

(506, 13)

In [100]:
len(X)

506

In [101]:
Y.shape

(506,)

In [102]:
print(type(Y))

<class 'numpy.ndarray'>


In [103]:
Y[1]

21.6

In [182]:
wold = np.random.rand(13)
wnew=np.random.rand(13)

In [183]:
wold

array([0.70667706, 0.45608818, 0.27800566, 0.74525299, 0.99410385,
       0.00986017, 0.79621829, 0.06230038, 0.8708567 , 0.39717912,
       0.38947062, 0.67541192, 0.49770078])

In [184]:
def grad(X,Y,w):    
    c=(-2*X[0])*(Y[0]-(X[0].dot(w)))
    return c    

In [185]:
for i in range(10):
    wnew=wold-grad(X,Y,wold)
    wold=wnew

In [186]:
wnew

array([ 2.57609556e+11, -1.74792880e+11,  7.90357478e+11,  1.67286844e+11,
        8.85025899e+10, -2.53859973e+11,  7.36491974e+10, -8.60455413e+10,
        6.03145797e+11,  4.09080594e+11,  8.95351624e+11, -2.70662413e+11,
        6.60045377e+11])

In [57]:
X[0]

array([-0.41978194,  0.28482986, -1.2879095 , -0.27259857, -0.14421743,
        0.41367189, -0.12001342,  0.1402136 , -0.98284286, -0.66660821,
       -1.45900038,  0.44105193, -1.0755623 ])